# Generated by Django 2.1.5 on 2019-04-30 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('in_game_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('order_id', models.CharField(default='None', max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
