# Generated by Django 2.1.5 on 2019-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
